In [73]:
import pandas as pd
unfiltered_data = pd.read_pickle('DataProject.pk')
unfiltered_data
# Displaying datda from pickle file

            date     asset         value        item
0     2020-01-01    ADAUSD      0.033813  daily_high
1     2020-01-01    BTCUSD   7254.330566  daily_high
2     2020-01-01    ETHUSD    132.835358  daily_high
3     2020-01-01   LINKUSD      1.851417  daily_high
4     2020-01-02    ADAUSD      0.033507  daily_high
...          ...       ...           ...         ...
3974  2020-12-30  LINK-USD     11.097195   daily_low
3975  2020-12-31   ADA-USD      0.176594   daily_low
3976  2020-12-31   BTC-USD  28201.992188   daily_low
3977  2020-12-31   ETH-USD    726.511902   daily_low
3978  2020-12-31  LINK-USD     10.999017   daily_low

[3979 rows x 4 columns]

In [74]:
unfiltered_data['asset'].unique()
# Note that there are similar tickers: For example, 'ADAUSD' and 'ADA-USD'
# Due to this error, python thinks that these two tickers are different but they are actually the same

array(['ADAUSD', 'BTCUSD', 'ETHUSD', 'LINKUSD', 'BTC-USD', 'ETH-USD',
       'LINK-USD', 'ADA-USD'], dtype=object)

In [75]:
unfiltered_data['asset'].value_counts()
# Looking at the 632 vs 633: this mean that there is a missing data point for 'ADA-USD'

asset
BTC-USD     633
ETH-USD     633
LINK-USD    633
ADA-USD     632
ADAUSD      362
BTCUSD      362
ETHUSD      362
LINKUSD     362
Name: count, dtype: int64

In [76]:
time_stamp = pd.to_datetime(unfiltered_data['date'])
unfiltered_data['date'] = time_stamp
# converting the date into pandas datetime values

In [77]:
index_data = unfiltered_data.set_index('date')
# making the date be our index
index_data

               asset         value        item
date
2020-01-01    ADAUSD      0.033813  daily_high
2020-01-01    BTCUSD   7254.330566  daily_high
2020-01-01    ETHUSD    132.835358  daily_high
2020-01-01   LINKUSD      1.851417  daily_high
2020-01-02    ADAUSD      0.033507  daily_high
...              ...           ...         ...
2020-12-30  LINK-USD     11.097195   daily_low
2020-12-31   ADA-USD      0.176594   daily_low
2020-12-31   BTC-USD  28201.992188   daily_low
2020-12-31   ETH-USD    726.511902   daily_low
2020-12-31  LINK-USD     10.999017   daily_low

[3979 rows x 3 columns]

In [78]:
unfiltered_data.groupby('asset')['date'].nunique()
# Finds the number of unique dates for each ticker

asset
ADA-USD     362
ADAUSD      362
BTC-USD     362
BTCUSD      362
ETH-USD     362
ETHUSD      362
LINK-USD    362
LINKUSD     362
Name: date, dtype: int64

In [79]:
unfiltered_data.groupby('item')['date'].nunique()
#Finds the number of unique dates for each item

item
daily_high    362
daily_low     271
daily_ret     362
Name: date, dtype: int64

In [80]:
unfiltered_data.groupby(['asset','item'])['date'].nunique()
# Finds  the number of unique dates for every combination of addet and item

asset     item
ADA-USD   daily_low     271
          daily_ret     361
ADAUSD    daily_high    362
BTC-USD   daily_low     271
          daily_ret     362
BTCUSD    daily_high    362
ETH-USD   daily_low     271
          daily_ret     362
ETHUSD    daily_high    362
LINK-USD  daily_low     271
          daily_ret     362
LINKUSD   daily_high    362
Name: date, dtype: int64

In [82]:
BTC_USD_data = index_data.loc[index_data['asset'] == 'BTC-USD']
# grabs the rows of 'BTC-USD'
BTC_USD_data

              asset         value       item
date
2020-01-01  BTC-USD   -999.000000  daily_ret
2020-01-02  BTC-USD   -999.000000  daily_ret
2020-01-03  BTC-USD   -999.000000  daily_ret
2020-01-04  BTC-USD   -999.000000  daily_ret
2020-01-05  BTC-USD   -999.000000  daily_ret
...             ...           ...        ...
2020-12-27  BTC-USD  25922.769531  daily_low
2020-12-28  BTC-USD  26207.640625  daily_low
2020-12-29  BTC-USD  25987.298828  daily_low
2020-12-30  BTC-USD  27360.089844  daily_low
2020-12-31  BTC-USD  28201.992188  daily_low

[633 rows x 3 columns]

In [83]:
BTC_USD_daily_low = index_data.loc[index_data['item'] == 'daily_low']
BTC_USD_daily_low
# grabs rows of 'BTC-USD' and 'daily_low'

               asset         value       item
date
2020-01-01   ADA-USD      0.032704  daily_low
2020-01-01   BTC-USD   7174.944336  daily_low
2020-01-01   ETH-USD      1.291983  daily_low
2020-01-01  LINK-USD      1.763420  daily_low
2020-01-02   ADA-USD      0.032448  daily_low
...              ...           ...        ...
2020-12-30  LINK-USD     11.097195  daily_low
2020-12-31   ADA-USD      0.176594  daily_low
2020-12-31   BTC-USD  28201.992188  daily_low
2020-12-31   ETH-USD    726.511902  daily_low
2020-12-31  LINK-USD     10.999017  daily_low

[1084 rows x 3 columns]

In [68]:
BTC_daily_low_dates = BTC_USD_daily_low.index
BTC_daily_low_dates
# available dates of 'BTC-USD' and 'daily_low'

DatetimeIndex(['2020-01-01', '2020-01-02', '2020-01-03', '2020-01-04',
               '2020-01-05', '2020-01-06', '2020-01-07', '2020-01-08',
               '2020-01-09', '2020-01-10',
               ...
               '2020-12-22', '2020-12-23', '2020-12-24', '2020-12-25',
               '2020-12-26', '2020-12-27', '2020-12-28', '2020-12-29',
               '2020-12-30', '2020-12-31'],
              dtype='datetime64[ns]', name='date', length=271, freq=None)

In [69]:
calendar_dates = pd.date_range('20200101','20201231', freq = 'D')
calendar_dates
#dates in a year

DatetimeIndex(['2020-01-01', '2020-01-02', '2020-01-03', '2020-01-04',
               '2020-01-05', '2020-01-06', '2020-01-07', '2020-01-08',
               '2020-01-09', '2020-01-10',
               ...
               '2020-12-22', '2020-12-23', '2020-12-24', '2020-12-25',
               '2020-12-26', '2020-12-27', '2020-12-28', '2020-12-29',
               '2020-12-30', '2020-12-31'],
              dtype='datetime64[ns]', length=366, freq='D')

In [70]:
calendar_dates.difference(daily_low_dates)
# Finding the missing dates of 'BTC-USD'

DatetimeIndex(['2020-04-17', '2020-07-02', '2020-07-03', '2020-07-04',
               '2020-07-05', '2020-07-06', '2020-07-07', '2020-07-08',
               '2020-07-09', '2020-07-10', '2020-07-11', '2020-07-12',
               '2020-07-13', '2020-07-14', '2020-07-15', '2020-07-16',
               '2020-07-17', '2020-07-18', '2020-07-19', '2020-07-20',
               '2020-07-21', '2020-07-22', '2020-07-23', '2020-07-24',
               '2020-07-25', '2020-07-26', '2020-07-27', '2020-07-28',
               '2020-07-29', '2020-07-30', '2020-07-31', '2020-08-01',
               '2020-08-02', '2020-08-03', '2020-08-04', '2020-08-05',
               '2020-08-06', '2020-08-07', '2020-08-08', '2020-08-09',
               '2020-08-10', '2020-08-11', '2020-08-12', '2020-08-13',
               '2020-08-14', '2020-08-15', '2020-08-16', '2020-08-17',
               '2020-08-18', '2020-08-19', '2020-08-20', '2020-08-21',
               '2020-08-22', '2020-08-23', '2020-08-24', '2020-08-25',
               '2020-08-26', '2020-08-27', '2020-08-28', '2020-08-29',
               '2020-08-30', '2020-08-31', '2020-09-01', '2020-09-02',
               '2020-09-03', '2020-09-04', '2020-09-05', '2020-09-06',
               '2020-09-07', '2020-09-08', '2020-09-09', '2020-09-10',
               '2020-09-11', '2020-09-12', '2020-09-13', '2020-09-14',
               '2020-09-15', '2020-09-16', '2020-09-17', '2020-09-18',
               '2020-09-19', '2020-09-20', '2020-09-21', '2020-09-22',
               '2020-09-23', '2020-09-24', '2020-09-25', '2020-09-26',
               '2020-09-27', '2020-09-28', '2020-09-29', '2020-09-30',
               '2020-10-09', '2020-10-12', '2020-10-13'],
              dtype='datetime64[ns]', freq=None)

In [86]:
ADA_USD_data = index_data.loc[index_data['asset'] =='ADA-USD']
ADA_USD_data

              asset     value       item
date
2020-01-02  ADA-USD -0.021131  daily_ret
2020-01-03  ADA-USD  0.043632  daily_ret
2020-01-04  ADA-USD  0.012142  daily_ret
2020-01-05  ADA-USD  0.003642  daily_ret
2020-01-06  ADA-USD  0.073471  daily_ret
...             ...       ...        ...
2020-12-27  ADA-USD  0.150378  daily_low
2020-12-28  ADA-USD  0.153445  daily_low
2020-12-29  ADA-USD  0.174039  daily_low
2020-12-30  ADA-USD  0.175681  daily_low
2020-12-31  ADA-USD  0.176594  daily_low

[632 rows x 3 columns]

In [88]:
ASA_USD_daily_low = ADA_USD_data.loc[ADA_USD_data['item'] == 'daily_low']
ASA_USD_daily_low

              asset     value       item
date
2020-01-01  ADA-USD  0.032704  daily_low
2020-01-02  ADA-USD  0.032448  daily_low
2020-01-03  ADA-USD  0.032491  daily_low
2020-01-04  ADA-USD  0.033872  daily_low
2020-01-05  ADA-USD  0.034545  daily_low
...             ...       ...        ...
2020-12-27  ADA-USD  0.150378  daily_low
2020-12-28  ADA-USD  0.153445  daily_low
2020-12-29  ADA-USD  0.174039  daily_low
2020-12-30  ADA-USD  0.175681  daily_low
2020-12-31  ADA-USD  0.176594  daily_low

[271 rows x 3 columns]

In [92]:
ASA_daily_low_dates = ASA_USD_daily_low.index
ASA_daily_low_dates

DatetimeIndex(['2020-01-01', '2020-01-02', '2020-01-03', '2020-01-04',
               '2020-01-05', '2020-01-06', '2020-01-07', '2020-01-08',
               '2020-01-09', '2020-01-10',
               ...
               '2020-12-22', '2020-12-23', '2020-12-24', '2020-12-25',
               '2020-12-26', '2020-12-27', '2020-12-28', '2020-12-29',
               '2020-12-30', '2020-12-31'],
              dtype='datetime64[ns]', name='date', length=271, freq=None)

In [94]:
calendar_dates.difference(ASA_daily_low_dates)

DatetimeIndex(['2020-04-17', '2020-07-02', '2020-07-03', '2020-07-04',
               '2020-07-05', '2020-07-06', '2020-07-07', '2020-07-08',
               '2020-07-09', '2020-07-10', '2020-07-11', '2020-07-12',
               '2020-07-13', '2020-07-14', '2020-07-15', '2020-07-16',
               '2020-07-17', '2020-07-18', '2020-07-19', '2020-07-20',
               '2020-07-21', '2020-07-22', '2020-07-23', '2020-07-24',
               '2020-07-25', '2020-07-26', '2020-07-27', '2020-07-28',
               '2020-07-29', '2020-07-30', '2020-07-31', '2020-08-01',
               '2020-08-02', '2020-08-03', '2020-08-04', '2020-08-05',
               '2020-08-06', '2020-08-07', '2020-08-08', '2020-08-09',
               '2020-08-10', '2020-08-11', '2020-08-12', '2020-08-13',
               '2020-08-14', '2020-08-15', '2020-08-16', '2020-08-17',
               '2020-08-18', '2020-08-19', '2020-08-20', '2020-08-21',
               '2020-08-22', '2020-08-23', '2020-08-24', '2020-08-25',
               '2020-08-26', '2020-08-27', '2020-08-28', '2020-08-29',
               '2020-08-30', '2020-08-31', '2020-09-01', '2020-09-02',
               '2020-09-03', '2020-09-04', '2020-09-05', '2020-09-06',
               '2020-09-07', '2020-09-08', '2020-09-09', '2020-09-10',
               '2020-09-11', '2020-09-12', '2020-09-13', '2020-09-14',
               '2020-09-15', '2020-09-16', '2020-09-17', '2020-09-18',
               '2020-09-19', '2020-09-20', '2020-09-21', '2020-09-22',
               '2020-09-23', '2020-09-24', '2020-09-25', '2020-09-26',
               '2020-09-27', '2020-09-28', '2020-09-29', '2020-09-30',
               '2020-10-09', '2020-10-12', '2020-10-13'],
              dtype='datetime64[ns]', freq=None)

In [112]:
unfiltered_data.groupby(['asset','item'])['date'].apply(lambda x: calendar_dates.difference(x))
# Shows the missing dates of data for every asset-item combo

asset     item
ADA-USD   daily_low     DatetimeIndex(['2020-04-17', '2020-07-02', '20...
          daily_ret     DatetimeIndex(['2020-01-01', '2020-04-17', '20...
ADAUSD    daily_high    DatetimeIndex(['2020-04-17', '2020-10-09', '20...
BTC-USD   daily_low     DatetimeIndex(['2020-04-17', '2020-07-02', '20...
          daily_ret     DatetimeIndex(['2020-04-17', '2020-10-09', '20...
BTCUSD    daily_high    DatetimeIndex(['2020-04-17', '2020-10-09', '20...
ETH-USD   daily_low     DatetimeIndex(['2020-04-17', '2020-07-02', '20...
          daily_ret     DatetimeIndex(['2020-04-17', '2020-10-09', '20...
ETHUSD    daily_high    DatetimeIndex(['2020-04-17', '2020-10-09', '20...
LINK-USD  daily_low     DatetimeIndex(['2020-04-17', '2020-07-02', '20...
          daily_ret     DatetimeIndex(['2020-04-17', '2020-10-09', '20...
LINKUSD   daily_high    DatetimeIndex(['2020-04-17', '2020-10-09', '20...
Name: date, dtype: object